### ISSUE TITLE
I did not understand your answer and did not know the reason for the closure, can you please explain my brother

### ISSUE THREAD

**Issue by GHOSt19dZ** [OpenVisionE2/NCam#5]
I did not understand your answer and did not know the reason for the closure, can you please explain my brother

**Comment by persianpros** [comment]
We're using https://github.com/OpenVisionE2/openvision-development-platform for compiling images, softcam and everything.

SH4 and NCam is ok too.

**Comment by GHOSt19dZ** [comment]
The problem is in liboscam_stapi5.a 
I spoke with the brother  RAED " fairbird "  and The file is checked
